### PR TITLE
Add is_explicit_relative property in AbstractImportObj

### LINKED ISSUE #17: Relative import sorted incorrect.
I am using [this](https://github.com/coldnight/reorder_python_imports), and I noticed the relative import sorted incorrect. Here is the code

```python
import pprint
from aspy.refactor_imports.import_obj import FromImport

objs = sorted([
    FromImport.from_str('from a import foo'),
    FromImport.from_str('from a.b import baz'),
    FromImport.from_str('from a import bar'),
    FromImport.from_str('from a import bar as buz'),
    FromImport.from_str('from a import bar as baz'),
    FromImport.from_str('from .a import bar as baz'),
    FromImport.from_str('from . import bar as baz'),
    FromImport.from_str('from .aa.bb import bar as baz'),
])
pprint.pprint([i.to_text() for i in objs])
```

Excepted: 

```text
[u'from a import bar\n',
 u'from a import bar as baz\n',
 u'from a import bar as buz\n',
 u'from a import foo\n',
 u'from a.b import baz\n',
 u'from .aa.bb import bar as baz\n',
 u'from .a import bar as baz\n',
 u'from . import bar as baz\n',
]
```

Got: 

```text
[u'from . import bar as baz\n',
 u'from .a import bar as baz\n',
 u'from .aa.bb import bar as baz\n',
 u'from a import bar\n',
 u'from a import bar as baz\n',
 u'from a import bar as buz\n',
 u'from a import foo\n',
 u'from a.b import baz\n']
```

### PR DESCRIPTION
**Pull request by coldnight**
Related PR: #18.
Closes #17.
Prepare for asottile/reorder_python_imports#20.

### CODE REVIEW

**Comment by coldnight** [comment]
@asottile Please review.

**Comment by asottile** [comment]
Looks good!

2 tiny minor things, one will be automatically fixed if you rebase so I won't even mention it, the other [is this](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#multi-line-method-invocation), not a big deal to fix though -- I am in the process of writing an automatic pre-commit hook to auto-fix this :)

At minimum, please rebase and run the tests once -- add trailing commas or not nbd

**Comment by asottile** [comment]
I'll merge in the morning -- getting late here where I'm visiting

**Comment by coldnight** [comment]
@asottile Ok,  I've rebased and fixed the other one problem.

**Comment by asottile** [comment]
Thanks for the PR! I'll make a release

**Comment by asottile** [comment]
This is part of 0.5.3

**Pull request merged**
